CREATE TABLE users (
	id SERIAL PRIMARY KEY,
	token TEXT NOT NULL UNIQUE
);

CREATE TABLE bins (
	id SERIAL PRIMARY KEY,
	user_id INT NOT NULL
		REFERENCES users(id) ON DELETE CASCADE,
	bin_name VARCHAR(50) UNIQUE NOT NULL,
	created_at TIMESTAMP DEFAULT NOW(),
	request_count INT NOT NULL DEFAULT 0
);

CREATE TABLE requests (
	id SERIAL PRIMARY KEY,
	bin_id INT NOT NULL
		REFERENCES bins(id) ON DELETE CASCADE,
	method VARCHAR(10),
	path TEXT NOT NULL,
	headers TEXT NOT NULL,
	body TEXT,
	received_at TIMESTAMP DEFAULT NOW()
);
